name: "PR Build and Comment"
description: "Build Flutter Android APK and comment on PR with download links"

inputs:
  pr_number:
    description: "Pull request number"
    required: true
  run_id:
    description: "GitHub Actions run ID"
    required: true
  repository:
    description: "Repository name"
    required: true
  pr_head_sha:
    description: "PR head commit SHA"
    required: true
  pr_head_ref:
    description: "PR head branch name"
    required: true
  github_server_url:
    description: "GitHub server URL"
    required: true
  github_token:
    description: "GitHub token for API access"
    required: true
 
runs:
  using: "composite"
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: pubspec.yaml
        cache: true

    - name: Fetch Dependencies
      shell: bash
      run: flutter pub get

    - name: Build Android APK
      shell: bash
      run: |
        flutter build apk --release
        if [ ! -f build/app/outputs/flutter-apk/app-release.apk ]; then
          echo "APK build failed"
          exit 1
        fi

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      id: upload-apk
      with:
        name: magic-epaper-apk-pr-${{ inputs.pr_number }}
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30

    - name: Get Artifact URLs
      id: artifacts
      shell: bash
      run: |
        # Get the run ID for artifact URLs
        RUN_ID=${{ inputs.run_id }}
        REPO=${{ inputs.repository }}
        
        # Get workflow URL as fallback
        WORKFLOW_URL="https://github.com/$REPO/actions/runs/$RUN_ID"
        
        # Get direct artifact URL from upload-artifact v4 output
        APK_URL="${{ steps.upload-apk.outputs.artifact-url }}"
        
        echo "WORKFLOW_URL=$WORKFLOW_URL" >> $GITHUB_OUTPUT
        echo "APK_URL=$APK_URL" >> $GITHUB_OUTPUT

    - name: Find existing comment
      uses: peter-evans/find-comment@v3
      id: find-comment
      with:
        token: ${{ inputs.github_token }}
        issue-number: ${{ inputs.pr_number }}
        comment-author: 'github-actions[bot]'
        body-includes: 'Build Artifacts Ready'
 
    - name: Create or update PR comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ inputs.github_token }}
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ inputs.pr_number }}
        edit-mode: replace
        body: |
          **Build Artifacts Ready**
          
          The Android build has completed successfully.
          
          | Platform | Download Link |
          |----------|---------------|
          | Android APK | [Download APK](${{ steps.artifacts.outputs.APK_URL }}) |
          
          [View workflow run](${{ steps.artifacts.outputs.WORKFLOW_URL }})

    - name: Build status comment on failure
      if: failure()
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ inputs.github_token }}
        issue-number: ${{ inputs.pr_number }}
        body: |
          **Build Failed**
          
          The Android APK build failed for this PR. Please check the [workflow logs](${{ inputs.github_server_url }}/${{ inputs.repository }}/actions/runs/${{ inputs.run_id }}) for details.