name: Magic Epaper PR CI

on:
  pull_request:
    branches:
      - main

jobs:
  common:
    name: Common Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Common Workflow
        uses: ./.github/actions/common

  android:
    name: Android Flutter Build
    needs: common
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Android Workflow
        uses: ./.github/actions/android
        with:
          pr_number: ${{ github.event.pull_request.number }}
          run_id: ${{ github.run_id }}
          repository: ${{ github.repository }}
          pr_head_sha: ${{ github.event.pull_request.head.sha }}
          pr_head_ref: ${{ github.event.pull_request.head.ref }}
          github_server_url: ${{ github.server_url }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  ios:
    name: iOS Flutter Build
    needs: common
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: iOS Workflow
        uses: ./.github/actions/ios
